#!/usr/bin/env bash

# Assert we're on Debian
if [ ! -f /etc/debian_version ]; then
    echo "Only Debian is supported." >&2
    exit 1
fi

# Ensure Mise is available
if ! command -v mise &> /dev/null; then
    curl https://mise.run | MISE_INSTALL_PATH=/usr/local/bin/mise sh
fi

# Ensure Fish is installed
if ! command -v fish &> /dev/null; then
    sudo apt-get install fish
    echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/4/Debian_Unstable/ /' | sudo tee /etc/apt/sources.list.d/shells:fish:release:4.list
    curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:4/Debian_Unstable/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_4.gpg > /dev/null
    sudo apt update
    sudo apt install fish
    chsh -s /usr/bin/fish
fi

# Ensure GNU Stow is installed
if ! command -v stow &> /dev/null; then
    sudo apt install stow
fi

stow --restow --no-folding --target ${HOME} config
